"use client"

import { useState } from "react"
import { ArrowUpRight, BrainCircuit, Code2, ExternalLink, Gamepad2, Globe2, Layers3, Menu, MessageCircle, Palette, Send, Smartphone, Sparkles, X, Zap } from "lucide-react"

const services = [
  [BrainCircuit, "AI applications", "Intelligent products that turn complex workflows into clear, useful experiences."],
  [Smartphone, "Mobile development", "Thoughtful iOS and Android apps engineered for real-world use."],
  [Globe2, "Web experiences", "Fast, expressive websites and custom web apps that move brands forward."],
  [Palette, "UI / UX design", "Distinctive product systems where every interaction feels intentional."],
  [Gamepad2, "Games & interactive", "Immersive digital worlds, prototypes and interactive applications."],
  [Layers3, "Digital solutions", "E-commerce, education, brand identity and the systems around them."],
]
const projects = [
  { number: "01", title: "Digital products, imagined clearly.", tag: "AI / WEB / PRODUCT", text: "We shape ambitious ideas into considered digital experiences — from first sketch to a product people return to.", className: "project-a" },
  { number: "02", title: "Built for the next chapter.", tag: "MOBILE / SYSTEMS", text: "A flexible development partner for businesses who need reliable technology without the noise.", className: "project-b" },
  { number: "03", title: "Beautifully useful by design.", tag: "BRAND / UX", text: "Brand worlds and interfaces with enough character to be remembered, and enough clarity to work.", className: "project-c" },
]
const process = ["Discover", "Plan", "Design", "Develop", "Test", "Launch", "Support"]

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [sent, setSent] = useState(false)
  return <main>
    <header className="container" style={{ position: "absolute", inset: "0 0 auto", zIndex: 10, paddingTop: 24 }}>
      <nav className="glass" style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "13px 16px 13px 20px", borderRadius: 999 }}>
        <a href="#top" className="display" style={{ fontSize: 18, fontWeight: 700, letterSpacing: ".04em" }}><span className="gold-text">NOVA</span> STUDIO<span style={{ color: "var(--gold)" }}>.</span></a>
        <div className="desktop-nav" style={{ display: "flex", alignItems: "center", gap: 28, fontSize: 13, color: "var(--muted)" }}><a href="#about">About</a><a href="#services">Services</a><a href="#work">Our work</a><a href="#contact">Contact</a></div>
        <a className="desktop-nav" href="#contact" style={{ background: "var(--gold)", color: "var(--ink)", padding: "10px 18px", borderRadius: 999, fontSize: 12, fontWeight: 700 }}>Start a project <ArrowUpRight size={14} style={{ verticalAlign: "-3px" }} /></a>
        <button aria-label={menuOpen ? "Close menu" : "Open menu"} className="mobile-menu" onClick={() => setMenuOpen(!menuOpen)} style={{ background: "none", border: 0, color: "white" }}>{menuOpen ? <X /> : <Menu />}</button>
      </nav>
      {menuOpen && <div className="glass mobile-links" style={{ marginTop: 8, borderRadius: 20, padding: 18, display: "grid", gap: 16 }}><a href="#about" onClick={() => setMenuOpen(false)}>About</a><a href="#services" onClick={() => setMenuOpen(false)}>Services</a><a href="#work" onClick={() => setMenuOpen(false)}>Our work</a><a href="#contact" onClick={() => setMenuOpen(false)}>Contact</a></div>}
    </header>

    <section id="top" className="grid-bg hero-orb" style={{ minHeight: "92vh", display: "flex", alignItems: "center", position: "relative", overflow: "hidden" }}>
      <div className="container" style={{ paddingTop: 130, paddingBottom: 90, position: "relative", zIndex: 1 }}><div style={{ maxWidth: 780 }}><div style={{ color: "var(--gold)", fontSize: 12, letterSpacing: ".22em", fontWeight: 700, marginBottom: 24 }}><Sparkles size={14} style={{ verticalAlign: "-2px", marginRight: 8 }} />INDEPENDENT DIGITAL STUDIO</div><h1 className="display" style={{ fontSize: "clamp(3.6rem, 9vw, 8rem)", lineHeight: .92, margin: 0, maxWidth: 850 }}>Make the <span className="gold-text">next</span> thing matter.</h1><p style={{ color: "var(--muted)", fontSize: 18, lineHeight: 1.7, maxWidth: 560, margin: "34px 0" }}>Nova Studio creates professional websites, mobile apps, AI solutions and digital products for businesses ready to move with purpose.</p><div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}><a href="#contact" style={{ background: "var(--gold)", color: "var(--ink)", padding: "15px 22px", borderRadius: 999, fontWeight: 700, fontSize: 14 }}>Start a project <ArrowUpRight size={16} style={{ verticalAlign: "-3px" }} /></a><a href="#work" className="glass" style={{ padding: "14px 22px", borderRadius: 999, fontWeight: 600, fontSize: 14 }}>View our work <ArrowUpRight size={16} style={{ verticalAlign: "-3px" }} /></a></div></div><div aria-hidden="true" style={{ position: "absolute", right: "-8%", bottom: "-10%", width: "48vw", height: "48vw", maxWidth: 620, maxHeight: 620, borderRadius: "50%", border: "1px solid rgba(220,182,106,.22)", boxShadow: "0 0 100px rgba(126,156,255,.12), inset 0 0 80px rgba(220,182,106,.08)" }}><div style={{ position: "absolute", inset: "12%", borderRadius: "50%", border: "1px solid rgba(126,156,255,.22)" }} /><div style={{ position: "absolute", inset: "28%", borderRadius: "50%", background: "radial-gradient(circle, rgba(220,182,106,.18), transparent 65%)" }} /></div></div>
    </section>

    <section id="about" className="container" style={{ padding: "130px 0 120px", display: "grid", gridTemplateColumns: "1fr 1.2fr", gap: "10vw", alignItems: "start" }}><div><p style={{ color: "var(--gold)", fontSize: 12, letterSpacing: ".18em", fontWeight: 700 }}>01 / ABOUT NOVA</p><h2 className="display" style={{ fontSize: "clamp(2.6rem, 5vw, 4.6rem)", lineHeight: 1, margin: "24px 0" }}>Technology with a point of view.</h2></div><div style={{ paddingTop: 36 }}><p style={{ color: "#d4d4d8", fontSize: 23, lineHeight: 1.45, margin: 0 }}>We are a digital technology and software development studio for people building what comes next.</p><p style={{ color: "var(--muted)", lineHeight: 1.8, marginTop: 26, maxWidth: 560 }}>From a sharp brand identity to a scalable application, Nova brings strategy, design and engineering into one focused team. The result is modern technology that feels human, performs beautifully and gives our clients room to grow.</p><div style={{ display: "flex", gap: 32, marginTop: 34, flexWrap: "wrap" }}><div><strong className="display" style={{ fontSize: 32 }}>01</strong><div style={{ color: "var(--muted)", fontSize: 12, marginTop: 5 }}>CLEAR THINKING</div></div><div><strong className="display" style={{ fontSize: 32 }}>∞</strong><div style={{ color: "var(--muted)", fontSize: 12, marginTop: 5 }}>ROOM TO GROW</div></div><div><strong className="display" style={{ fontSize: 32 }}>24/7</strong><div style={{ color: "var(--muted)", fontSize: 12, marginTop: 5 }}>CURIOUS MINDS</div></div></div></div></section>

    <section id="services" style={{ borderTop: "1px solid var(--line)", padding: "110px 0" }}><div className="container"><div style={{ display: "flex", justifyContent: "space-between", gap: 24, alignItems: "end", marginBottom: 46, flexWrap: "wrap" }}><div><p style={{ color: "var(--gold)", fontSize: 12, letterSpacing: ".18em", fontWeight: 700 }}>02 / CAPABILITIES</p><h2 className="display" style={{ fontSize: "clamp(2.5rem, 5vw, 4.5rem)", margin: "20px 0 0" }}>Built around your ambition.</h2></div><p style={{ color: "var(--muted)", maxWidth: 280, lineHeight: 1.6, margin: 0 }}>One studio, the strategic range to take an idea from spark to shipped.</p></div><div className="service-grid">{services.map(([Icon, title, text]) => <article className="glass hover-lift" key={title as string} style={{ padding: 24, borderRadius: 22, minHeight: 220 }}><Icon color="var(--gold)" size={27} /><h3 className="display" style={{ fontSize: 22, margin: "42px 0 10px" }}>{title as string}</h3><p style={{ color: "var(--muted)", fontSize: 14, lineHeight: 1.6, margin: 0 }}>{text as string}</p></article>)}</div></div></section>

    <section id="work" style={{ background: "#0b0d14", padding: "120px 0" }}><div className="container"><p style={{ color: "var(--gold)", fontSize: 12, letterSpacing: ".18em", fontWeight: 700 }}>03 / SELECTED WORK</p><div style={{ display: "flex", justifyContent: "space-between", alignItems: "end", marginBottom: 48, gap: 20 }}><h2 className="display" style={{ fontSize: "clamp(2.5rem, 5vw, 4.5rem)", margin: "20px 0 0" }}>Work in progress.<br /><span style={{ color: "var(--muted)" }}>Ideas in motion.</span></h2><Code2 color="var(--gold)" size={34} /></div><div style={{ display: "grid", gap: 18 }}>{projects.map((project) => <article className={`project-card ${project.className}`} key={project.number} style={{ minHeight: 360, borderRadius: 26, padding: "30px", display: "flex", flexDirection: "column", justifyContent: "space-between", overflow: "hidden", position: "relative" }}><div style={{ display: "flex", justifyContent: "space-between", fontSize: 12, letterSpacing: ".16em", color: "rgba(255,255,255,.65)" }}><span>{project.number}</span><span>{project.tag}</span></div><div style={{ maxWidth: 440, position: "relative" }}><h3 className="display" style={{ fontSize: "clamp(2rem, 4vw, 3.5rem)", lineHeight: 1, margin: "0 0 14px" }}>{project.title}</h3><p style={{ color: "rgba(255,255,255,.68)", lineHeight: 1.6, maxWidth: 380, margin: 0 }}>{project.text}</p></div></article>)}</div></div></section>

    <section className="container" style={{ padding: "120px 0" }}><div style={{ display: "grid", gridTemplateColumns: "1fr 1.4fr", gap: "10vw" }}><div><p style={{ color: "var(--gold)", fontSize: 12, letterSpacing: ".18em", fontWeight: 700 }}>04 / THE NOVA METHOD</p><h2 className="display" style={{ fontSize: "clamp(2.6rem, 5vw, 4.6rem)", lineHeight: 1, margin: "24px 0" }}>A better way to build.</h2></div><div className="process-list">{process.map((step, i) => <div key={step} style={{ display: "flex", alignItems: "center", gap: 22, padding: "20px 0", borderBottom: "1px solid var(--line)" }}><span style={{ color: "var(--gold)", fontSize: 12 }}>0{i + 1}</span><span className="display" style={{ fontSize: 28 }}>{step}</span><ArrowUpRight size={18} color="var(--muted)" style={{ marginLeft: "auto" }} /></div>)}</div></div></section>

    <section id="contact" style={{ padding: "110px 0", background: "linear-gradient(125deg, #171a29, #0a0b10 55%, #211b13)" }}><div className="container contact-grid"><div><p style={{ color: "var(--gold)", fontSize: 12, letterSpacing: ".18em", fontWeight: 700 }}>05 / START A PROJECT</p><h2 className="display" style={{ fontSize: "clamp(3rem, 7vw, 6rem)", lineHeight: .95, margin: "24px 0" }}>Let&apos;s make<br /><span className="gold-text">something</span>.</h2><p style={{ color: "var(--muted)", lineHeight: 1.7, maxWidth: 390 }}>Have an idea, a challenge, or a product that needs a clearer future? Tell us a little about it.</p><a href="mailto:hello@novastudio1.online" style={{ display: "inline-flex", alignItems: "center", gap: 10, color: "var(--gold)", marginTop: 20 }}>hello@novastudio1.online <ArrowUpRight size={16} /></a></div><form className="glass" onSubmit={(e) => { e.preventDefault(); setSent(true) }} style={{ padding: 28, borderRadius: 24, display: "grid", gap: 16 }}><label>Your name<input required name="name" placeholder="Jane Smith" /></label><label>Email address<input required type="email" name="email" placeholder="jane@company.com" /></label><label>Tell us about the project<textarea required name="message" rows={5} placeholder="What are you building?" /></label><button type="submit" style={{ border: 0, background: "var(--gold)", color: "var(--ink)", padding: 15, borderRadius: 999, fontWeight: 700, cursor: "pointer" }}>{sent ? "Message ready — thank you" : "Send inquiry"} <Send size={15} style={{ verticalAlign: "-2px" }} /></button></form></div></section>

    <footer style={{ padding: "32px 0", borderTop: "1px solid var(--line)" }}><div className="container" style={{ display: "flex", justifyContent: "space-between", gap: 20, flexWrap: "wrap", color: "var(--muted)", fontSize: 12 }}><span className="display" style={{ color: "white", fontWeight: 700, letterSpacing: ".04em" }}><span className="gold-text">NOVA</span> STUDIO.</span><span>Digital products, built brilliantly.</span><span>© {new Date().getFullYear()} Nova Studio</span></div></footer>
    <style jsx>{` .mobile-menu,.mobile-links{display:none}.service-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.project-a{background:radial-gradient(circle at 75% 30%,#49598b,transparent 30%),linear-gradient(120deg,#1b223b,#10131e)}.project-b{background:radial-gradient(circle at 70% 30%,#775d38,transparent 30%),linear-gradient(120deg,#332719,#151310)}.project-c{background:radial-gradient(circle at 80% 20%,#584478,transparent 28%),linear-gradient(120deg,#241c35,#111019)}label{display:grid;gap:8px;color:#d5d5da;font-size:12px}input,textarea{background:rgba(0,0,0,.22);border:1px solid var(--line);border-radius:12px;padding:13px;color:white;font:inherit;outline:none}input:focus,textarea:focus{border-color:var(--gold)}.contact-grid{display:grid;grid-template-columns:1fr 1fr;gap:10vw;align-items:center}@media(max-width:760px){.desktop-nav{display:none!important}.mobile-menu{display:block}.service-grid{grid-template-columns:1fr 1fr}.contact-grid{grid-template-columns:1fr}.container>div[style*='grid-template-columns: 1fr 1.2fr'],.container>div[style*='grid-template-columns: 1fr 1.4fr']{grid-template-columns:1fr!important;gap:28px!important}.container>div[style*='grid-template-columns: 1fr 1.2fr']>div:nth-child(2),.container>div[style*='grid-template-columns: 1fr 1.4fr']>div:nth-child(2){padding-top:0}.hero-orb>div{padding-top:120px}.process-list{margin-top:0}}@media(max-width:460px){.service-grid{grid-template-columns:1fr}.project-card{min-height:420px!important}}`}</style>
  </main>
}
